---
# ====== Application: Bachelor Project System ================
identification: 
  name: Bachelor Project System
  alias: FINAL-PROJECT
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Role-Based # 26802079007972172610

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_TESTMMNAZARI

globalization: 
  primary-language: Farsi (fa)
  document-direction: Right-To-Left
  language-derived-from: Application Primary Language
  automatic-time-zone: true
  automatic-csv-encoding: true

application-format-masks: 
  date: fmDay, fmDD fmMonth, YYYY
  timestamp: 'DD-MON-YYYY HH24:MI'
  timestamp-time-zone: 'DD-MON-YYYY HH24:MI'

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--default
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 26793621837990812306

navigation-bar: 
  implementation: List
  list: Navigation Bar # 26794314337954812507
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Final Project

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 26793616876225812303
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15555273861578

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 26793617127827812303
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 15555273861595

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 26793617442706812304
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 15555273861605

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 26793617728245812304
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 15555273861618

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 26793618020902812304
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 15555273861629

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 26793618364705812304
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 15555273861639

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 26793618630568812304
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 15555273861652

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 26793618907365812304
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 15555273861665

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 26793619254794812305
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15555273861672

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 26793619549795812305
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15555273861683

- # ====== Component Setting: NATIVE_IR ========================
  id: 26793619861564812305
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15555273861691

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 26793620182731812305
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15555273861703

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 26793620498348812305
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15555273861718

